version: "3.9"

services:
  app:
    image: hashicorp/http-echo:0.2.3
    command:
      - "-listen=:8080"
      - "-text={\"status\":\"ok\",\"service\":\"app\",\"env\":\"${ENV_NAME:-local}\"}"
   # healthcheck:
    ##  test: ["CMD", "nc", "-z", "localhost", "8080"]
      #interval: 10s
      #timeout: 2s
      #retries: 5

  proxy:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 2s
      retries: 5
